name: Process Water Quality Images
on:
  push:
    paths:
      - 'images/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  process-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install system dependencies for Sharp
      run: |
        sudo apt-get update
        sudo apt-get install -y libvips-dev
    
    - name: Get changed files
      id: changed-files
      run: |
        # Get the list of changed image files
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '^images/' | grep -E '\.(jpg|jpeg|png|webp|tiff|bmp)
    
    - name: Process images
      if: steps.changed-files.outputs.has_files == 'true'
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        NODE_ENV: production
      run: |
        echo "🚀 Starting image processing workflow..."
        
        # Read files from temporary file
        CHANGED_FILES=$(cat /tmp/changed_files.txt)
        echo "Files to process: $CHANGED_FILES"
        
        # Process each file
        SUCCESS_COUNT=0
        TOTAL_COUNT=0
        
        # Convert to array and process
        while IFS= read -r file; do
          if [ -n "$file" ]; then
            TOTAL_COUNT=$((TOTAL_COUNT + 1))
            echo "🔄 Processing file $TOTAL_COUNT: $file"
            
            if [ -f "$file" ]; then
              # Run the processing script
              if node scripts/process-image.js "$file"; then
                echo "✅ Successfully processed $file"
                SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
              else
                echo "❌ Failed to process $file"
                exit 1
              fi
            else
              echo "⚠️  File not found: $file"
            fi
          fi
        done < /tmp/changed_files.txt
        
        echo "📊 Processing Summary:"
        echo "Total files: $TOTAL_COUNT"
        echo "Successfully processed: $SUCCESS_COUNT"
        echo "🎉 All images processed successfully!"
        
        # Save processed files list for cleanup
        cp /tmp/changed_files.txt /tmp/processed_files.txt
    
    - name: Clean up processed images
      if: steps.changed-files.outputs.has_files == 'true'
      run: |
        echo "🧹 Starting cleanup of processed images..."
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Remove processed images
        DELETED_FILES=""
        DELETED_COUNT=0
        
        # Read from processed files list
        while IFS= read -r file; do
          if [ -n "$file" ] && [ -f "$file" ]; then
            echo "🗑️  Deleting $file"
            git rm "$file"
            DELETED_FILES="$DELETED_FILES $file"
            DELETED_COUNT=$((DELETED_COUNT + 1))
          fi
        done < /tmp/processed_files.txt
        
        # Commit and push changes if files were deleted
        if [ $DELETED_COUNT -gt 0 ]; then
          git commit -m "🧹 Remove $DELETED_COUNT processed images [skip ci]"
          git push
          echo "✅ Cleanup completed - deleted $DELETED_COUNT files"
          echo "Deleted files: $DELETED_FILES"
        else
          echo "ℹ️  No files to clean up"
        fi
    
    - name: Post-processing summary
      if: always()
      run: |
        echo "📊 Post-processing summary:"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Workflow status: ${{ job.status }}"
        
        # Show processed files if they exist
        if [ -f "/tmp/processed_files.txt" ]; then
          echo "Processed files:"
          cat /tmp/processed_files.txt
        fi
        
        # Log final status
        if [ "${{ job.status }}" = "success" ]; then
          echo "🎉 Water quality image processing workflow completed successfully!"
        else
          echo "❌ Workflow completed with issues"
        fi
    
    - name: Notify completion
      if: success()
      run: |
        echo "🔔 Processing notification:"
        echo "- Repository: ${{ github.repository }}"
        echo "- Branch: ${{ github.ref_name }}"
        echo "- Commit: ${{ github.sha }}"
        echo "- Timestamp: $(date -u)"
        
        # Show final file count
        if [ -f "/tmp/processed_files.txt" ]; then
          PROCESSED_COUNT=$(wc -l < /tmp/processed_files.txt)
          echo "- Files processed and cleaned: $PROCESSED_COUNT"
        fi || echo "")
        echo "Changed files: $CHANGED_FILES"
        
        # Save files to a temporary file for better handling
        echo "$CHANGED_FILES" > /tmp/changed_files.txt
        
        # Set outputs
        echo "files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Convert to array for easier processing
        if [ -n "$CHANGED_FILES" ]; then
          echo "has_files=true" >> $GITHUB_OUTPUT
          echo "File count: $(echo "$CHANGED_FILES" | wc -l)"
        else
          echo "has_files=false" >> $GITHUB_OUTPUT
          echo "No image files found to process"
        fi
    
    - name: Process images
      if: steps.changed-files.outputs.has_files == 'true'
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        NODE_ENV: production
      run: |
        echo "🚀 Starting image processing workflow..."
        
        # Process each changed image file
        for file in ${{ steps.changed-files.outputs.files }}; do
          if [ -f "$file" ]; then
            echo "🔄 Processing $file"
            node scripts/process-image.js "$file"
            
            # Check if processing was successful
            if [ $? -eq 0 ]; then
              echo "✅ Successfully processed $file"
            else
              echo "❌ Failed to process $file"
              exit 1
            fi
          else
            echo "⚠️  File not found: $file"
          fi
        done
        
        echo "🎉 All images processed successfully!"
    
    - name: Clean up processed images
      if: steps.changed-files.outputs.has_files == 'true'
      run: |
        echo "🧹 Starting cleanup of processed images..."
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Remove processed images
        DELETED_FILES=""
        for file in ${{ steps.changed-files.outputs.files }}; do
          if [ -f "$file" ]; then
            echo "🗑️  Deleting $file"
            git rm "$file"
            DELETED_FILES="$DELETED_FILES $file"
          fi
        done
        
        # Commit and push changes if files were deleted
        if [ -n "$DELETED_FILES" ]; then
          git commit -m "🧹 Remove processed images: $DELETED_FILES [skip ci]"
          git push
          echo "✅ Cleanup completed - deleted files: $DELETED_FILES"
        else
          echo "ℹ️  No files to clean up"
        fi
    
    - name: Post-processing summary
      if: always()
      run: |
        echo "📊 Post-processing summary:"
        echo "Files processed: ${{ steps.changed-files.outputs.files }}"
        echo "Cleanup completed: ${{ steps.changed-files.outputs.has_files }}"
        echo "Workflow status: ${{ job.status }}"
        
        # Log final status
        if [ "${{ job.status }}" = "success" ]; then
          echo "🎉 Water quality image processing workflow completed successfully!"
        else
          echo "❌ Workflow completed with issues"
        fi
    
    - name: Notify completion
      if: success()
      run: |
        echo "🔔 Processing notification:"
        echo "- Repository: ${{ github.repository }}"
        echo "- Branch: ${{ github.ref_name }}"
        echo "- Commit: ${{ github.sha }}"
        echo "- Processed files: ${{ steps.changed-files.outputs.files }}"
        echo "- Timestamp: $(date -u)"
